# Generated by Django 3.2.23 on 2023-12-30 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('instrument', models.CharField(choices=[('vocalist_wanted', 'Vocalist wanted'), ('vocalist_here', 'Vocalist here'), ('guitarist_wanted', 'Guitarist wanted'), ('guitarist_here', 'Guitarist here'), ('bassist_wanted', 'Bassist wanted'), ('bassist_here', 'Bassist here'), ('keyboardist_wanted', 'Keyboardist wanted'), ('keyboardist_here', 'Keyboardist here'), ('drummer_wanted', 'Drummer wanted'), ('drummer_here', 'Drummer here'), ('other', 'Other')], max_length=30)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('metal', 'Metal'), ('pop', 'Pop'), ('country', 'Country'), ('jazz', 'Jazz'), ('folk', 'Folk'), ('electronic_dance_music', 'Electronic Dance Music'), ('r&b', 'R&B'), ('classical', 'Classical'), ('other', 'Other')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
