# Generated by Django 3.2.23 on 2024-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20231231_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
