# Generated by Django 3.2.23 on 2024-01-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240110_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('select_genre', 'Select genre...'), ('blues', 'Blues'), ('classical', 'Classical'), ('country', 'Country'), ('electronic_dance_music', 'Electronic Dance Music'), ('folk', 'Folk'), ('jazz', 'Jazz'), ('metal', 'Metal'), ('pop', 'Pop'), ('r&b', 'R&B'), ('rock', 'Rock'), ('soul', 'Soul'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='instrument',
            field=models.CharField(choices=[('select_instrument', 'Select instrument...'), ('bassist_here', 'Bassist here'), ('bassist_wanted', 'Bassist wanted'), ('drummer_here', 'Drummer here'), ('drummer_wanted', 'Drummer wanted'), ('guitarist_here', 'Guitarist here'), ('guitarist_wanted', 'Guitarist wanted'), ('keyboardist_here', 'Keyboardist/pianist here'), ('keyboardist_wanted', 'Keyboardist/pianist wanted'), ('vocalist_wanted', 'Vocalist wanted'), ('vocalist_here', 'Vocalist here'), ('other', 'Other')], max_length=30),
        ),
    ]
