# Generated by Django 3.2.23 on 2023-12-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_user_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default-picture_xzjf4x', upload_to='profile_images/'),
        ),
    ]
