# Generated by Django 4.2.13 on 2024-05-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
    ]
