# Generated by Django 3.2.23 on 2024-01-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20231231_0002'),
        ('interested', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='posts.post'),
        ),
    ]
